### PR TITLE
Selecting to download support for current directory

### PR DESCRIPTION
**Pull request by myl7**
The PR adds a new column (by moving `col-span-1` from filename column to the new column) to provide selection checkbox and download button to download selected files (excluding folders) in the current directory. The files will be compressed into one single zip file and then passed to browser to download. (In the process, data is stored in blobs so there should not be huge memory consumption, but I have not take a benchmark)

The reason why selecting folders is not implemented is that, while recursively go through the folders is difficult according to https://github.com/spencerwooo/onedrive-vercel-index/discussions/136#discussioncomment-1450067 , folders may be password-protected and it seems hard to find a proper way to ask users for the multiply passwords. Anyway, file selecting support should be enough to help people who store tons of files without packaging on the app.

As for pagination, the PR reuse the SWR hook result so pagination should not be broken.

A demo can (still) be found on https://share.myl.moe/

Ref: discussion #136 issue #143

### CODE REVIEW

**Comment by tismega** [comment]
请问是否能不下载.password?

**Comment by tismega** [comment]
非常谢谢!

**Review by spencerwooo — COMMENTED** [review]
image

The only one thing I don't like about this implementation is the way the download button takes up an empty column. I know it's with grid columns and that `12` cols is the max number tailwind specifies. I couldn't think of a better solution other than maybe adding the button as a floating action button which appears on a fixed bottom right position when files to download are selected. Other than this, I think we are good to go.

**Comment by myl7** [comment]
(Sorry for misclick)

If we are going to add a download button on a fixed bottom right position, the base bottom seems hard to choose. File listing pages do not have square bottoms like file detail pages, as it needs to use page bottom to show readme content.

Maybe we can add the download button between readme content and file list, but it can cause content shrinking when it appears and disappears. And it is too far from the selecting checkbox in the title row.

Or we can add the download floating action button on the page right bottom absolutely (personally preferred). The problem is we need to ensure other functions requiring page-level floating action button in the future can intergrate well with the selecting to download function.

When implementing the function, I also referred to some similar projects. Currently I only know https://github.com/lrsjng/h5ai has selected downloading, which uses header buttons. It doesnt seem graceful enough IMO.

**Review by spencerwooo — APPROVED** [review]
Button to download all files shows disabled by default and will be enabled when files are selected. Merging this as is.

**Pull request merged**
