### PR TITLE
Implement password hashing and allow more variables to be set via environment variables

### PR DESCRIPTION
**Pull request by paz**

### CODE REVIEW

**Comment by opoet** [comment]
好耶ヽ(✿ﾟ▽ﾟ)ノ

**Comment by spencerwooo** [comment]
@paz appreciate the effort for implementing hash to protected routes, but why are we adding these extra non-sensitive configs to environment variables?

1. vercel have a limited environment variable storage (#19) and it would be a waste to store these extra data
2. additionally, if users were to fork this repo and deploy it on their own, they can't avoid changing file contents and making customisations

my main point is that extracting these configs to environment variables _does not_ help them avoid potential upcoming conflicts when they update their forks. hence i would prefer not making these extra changes to the way configurations are handled. thx

**Comment by paz** [comment]
Ah i see, I did not know it is limited, well the environment variables are OPTIONAL, leaving them blank means it just uses the config file instead. I prefer to use environment variables, but that doesnt mean its forcing others to do the same.

**Comment by opoet** [comment]
我也这样觉得，环境变量空间有限，而且修改config也挺便捷。另外哈希密码挺不错的😋🌼

**Comment by paz** [comment]
I will add password hashing option to config aswell

**Comment by spencerwooo** [comment]
Core logics implemented in #83, closing this for now.

**Pull request closed without merging**
