### PR TITLE
Turkish translation original

### PR DESCRIPTION
**Pull request by rinrinx2**
update turkish language

### CODE REVIEW

**Comment by spencerwooo** [comment]
Thanks, but this is not complete yet. Would still need to update a few files before merging this - will check when I have time ;)

**Comment by kamileecher** [comment]
Thanks bro, send a notification when it's done.  I will add the missing translations
@spencerwooo

**Review by kamileecher — COMMENTED** [review]
Missing places have been rearranged

**Comment by spencerwooo** [comment]
I'm a bit confused, there are two Turkish translation PRs and none of them are complete. Which PR should I focus on reviewing (and I do not understand Turkish at all). :(

**Comment by spencerwooo** [comment]
FYI, if this one is the complete version, give me a ping and I'll update the rest of the configurations as needed - as there's a bit of more work to do before the translations can be pushed live.

**Comment by spencerwooo** [comment]
And also what is the relationship between this PR and #591 ?

**Pull request merged**
