### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by therockstarind**

### CODE REVIEW

**Comment by spencerwooo** [comment]
Please put all your changes in a single PR, I closed all other PRs that you made as they were a bit of a mess. Merge all your changes here, thanks. :)

**Comment by therockstarind** [comment]
well sorry for mess im not that much good at these things so sorry for that.

**Comment by kamileecher** [comment]
This translation belongs to me, I created a request before, why did you create a request again?

**Comment by therockstarind** [comment]
@kamileecher i just re posted to pull request

**Comment by kamileecher** [comment]
no problem bro.  We only made two requests, the admin was confused.
🤣🤣🤣

**Comment by myl7** [comment]
Close since #582 has been merged

**Pull request closed without merging**
