### PR TITLE
I18n support

### PR DESCRIPTION
**Pull request by myl7**
Ref discussion #346 and reply in discussion #352

The PR adds i18n support for the app.

it adds packages `next-i18next`, which provides i18n loading to work with Next builtin i18n routing, and ~~`i18next-scanner`~~`i18next-parser`, which generates files containing words requiring translations. All need to do for original English words is just to wrap them with function `t()` which is from `useTranslation()` hook, and then run `npm run extract`.

~~Though not comprehensive enough, the PR contains some zh-CN translations. I will try to hook all words later.~~ All possible points I can find have been hooked

(BTW, due to next-i18next which follows standard faithfully, it has to be zh-CN other than zh-cn, otherwise it would not work though no error would be shown.)

### CODE REVIEW

**Comment by spencerwooo** [comment]
Preview link is not working? Does this PR bring additional build steps to the project?

**Comment by myl7** [comment]
`next-i18next` does not need extra build steps since the translations are loaded in `getServerSideProps`, which runs in SSR of edge runtime.

However, the API routes wiredly do not work, simply replying 404. Could you check Vercel console and get the detailed log of API routes?

**Comment by myl7** [comment]
Seems Vercel even does not deploy API routes after detecting them. I will later do some more experiments to find a solution.

**Comment by myl7** [comment]
Well... It is the trailing slash prolem. Now preview should be OK.

**Comment by myl7** [comment]
All possible points I can find have been hooked.

**Comment by opoet** [comment]
搜索界面有问题
image

**Comment by myl7** [comment]
> 

Fixed

**Comment by spencerwooo** [comment]
These pages are not properly i18n-ed it seems?

- https://onedrive-vercel-index-qtxoila00-spencerwoo.vercel.app/zh-CN/onedrive-vercel-index-oauth/step-1/
- https://onedrive-vercel-index-qtxoila00-spencerwoo.vercel.app/zh-CN/onedrive-vercel-index-oauth/step-2/
- https://onedrive-vercel-index-qtxoila00-spencerwoo.vercel.app/zh-CN/onedrive-vercel-index-oauth/step-3/

**Comment by myl7** [comment]
Fixed.

Additionally, `i18next-parser` seems unable to parse entity encoding in `<Trans>` component. To resolve it I have replaced all `$apos;` with `'`. Replacing them with any value is OK since the actually displayed content is set in locale JSONs.

**Comment by spencerwooo** [comment]
> Edit: Oh, now I have known why &apos; is used...

Yes, Next.js won't allow single quotes and such, and require them to be escaped.

https://nextjs.org/docs/basic-features/eslint#core-web-vitals

**Comment by myl7** [comment]
Putting single quotes into string literal works though not so nice.

**Comment by spencerwooo** [comment]
I mean, you can always disable eslint for those lines ;)

```js
// eslint-disable-next-line react/no-unescaped-entities
```

**Comment by myl7** [comment]
( 'ﾛ')!!! You are right. Later after dinner I will edit them back.

**Review by spencerwooo — APPROVED** [review]
👍 Good to go

**Pull request merged**
