### PR TITLE
OAuth inside main project with public client ID and secret

### LINKED ISSUE #199: Using a public ClientID/ClientSecret for all deployments
According to [rclone/rclone#309](https://github.com/rclone/rclone/issues/309) and [rclone/rclone#372](https://github.com/rclone/rclone/issues/372), providing a public ClientID/ClientSecret in the main repo (here) for all forked deployments should be possible. This would potentially resolve or supersede a number of issues related to tokens/deployments:

- Tokens larger than Vercel's limitations:
   - #195
   - #19
- Failed or confusing deployments:
   - #196
   - #194

> This idea is first mentioned in: [onedrive-cf-index#191](https://github.com/spencerwooo/onedrive-cf-index/issues/191)

### PR DESCRIPTION
**Pull request by spencerwooo**
OAuth process as in: https://docs.microsoft.com/en-us/graph/auth-v2-user

Closes #199, #200, and #208

Sneak peeks:

image

image

image

### CODE REVIEW

**Comment by spencerwooo** [comment]
Nope, using `/tmp` or in memory key value storage is no workaround, might as well use Vercel's own integrations.

Redis: https://vercel.com/integrations/upstash

**Comment by coldpub** [comment]
Create Your Redis Client？
If you completed the integration steps above and redeploy your app; the REDIS_URL environment variable will be accessible inside your Vercel application. You can create your client as below:？

What should I do here?

**Comment by spencerwooo** [comment]
1. first, add any vercel accessible redis url inside vercel env var, if you use upstash, this step is automatic
2. next, change any necessary config in your github project and redeploy to vercel
3. profit

you don't need to worry about the 'create your redis client' step in the upstash documentation, that's for me to worry about. ;)

**Comment by coldpub** [comment]
> 1. 首先，在 vercel env var 中添加任何 vercel 可访问的 redis url，如果你使用 upstash，这一步是自动的
> 2. 接下来，更改 github 项目中的任何必要配置并重新部署到 vercel
> 3. 利润
> 
> 您无需担心 upstash 文档中的“创建您的 redis 客户端”步骤，这是我需要担心的。;)

yes I set it up, re-deploy  404

**Comment by coldpub** [comment]
> 1. 首先，在 vercel env var 中添加任何 vercel 可访问的 redis url，如果你使用 upstash，这一步是自动的
> 2. 接下来，更改 github 项目中的任何必要配置并更新到 vercel
> 3. 收益
> 
> 您无需担心 upstash 文档的“创建您的 redis 客户端”步骤，这是我需要担心的。;)

Oops, that's a four-oh-four.
Request failed with status code 500
Press F12 and open devtools for more details, or seek help at onedrive-vercel-index discussions.

**Comment by spencerwooo** [comment]
你的项目没更新

**Comment by coldpub** [comment]
> 你的项目没更新

需要重新复制onedrive-vercel-index吗

**Pull request merged**
